### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by YaLTeR** [cpw/inventorysorter#10]
Would be nice to have a simple config to be able to enable / disable the sorting or wheel individually.

**Comment by cpw** [comment]
Maybe soon

**Comment by Jiraiyah** [comment]
Also would be nice if there was a keybind so that we could bind any key from keyboard for sorting, i personally don't like mouse wheel click, had many mouses lost the wheel accuracy because of that.

**Comment by cpw** [comment]
Configuring the key bindings is not going to happen sadly. The way the game dispatches keybindings and especially mousewheel related events would make it logically impossible to do. If you go to a keybinding and try "scrollwheel up" as a key binding right now, you'll see that it'll just ignore you.

I may do something for sorting, but it turns out that is a mess of horribleness too, so I'm definitely not very inclined to do so at present.

**Comment by YaLTeR** [comment]
Not even an on/off switch? :/
