### ISSUE TITLE
Item

### ISSUE THREAD

**Issue by MrTubzy456** [cpw/inventorysorter#18]
Ok, there's two mods at work here but I don't know which is causing this issue so you both get a post. When using the ender bag, from Ender Utilities, and you middle click to sort your inventory from cpw's inventory sorting mod, everything dupes. Everything in the bag and your inventory. It'll fill your inventory and all of the excess won't be duped.

Here's the link to the post I made on the other mods git: https://github.com/maruohon/enderutilities/issues/18

**Comment by maruohon** [comment]
The main issue here is that many of my inventories support stacking items in stacks larger than the regular maxStackSize, and Inventory Sorter doesn't seem to support that. My custom slots do implement Slot#getItemStackLimit(ItemStack) so that would be a way to know what the maximum stack size is in my inventories at least...

One thing that is also kind of related to this: from a quick glance at Inventory Sorter's code, it doesn't seem to have any recognition for SlotItemHandler type slots, which makes this issue worse for my inventories, because InventorySorter thinks that all the slots are in the same inventory. This is the also related to https://github.com/MinecraftForge/MinecraftForge/pull/2884

I have "fixed" this conflict/issue in my dev version by using a MouseInputEvent at priority LOW and calling GuiScreen#handleMouseInput() myself and then canceling the event, so that Inventory Sorter won't work in any of my inventories... (I also use middle mouse click for some custom actions in some of my GUIs, so that's another reason I need to disable Inventory Sorter in my GUIs.)
