### ISSUE TITLE
Need for Fabric

### ISSUE THREAD

**Issue by Vitokhv** [cpw/inventorysorter#192]
Need for Fabric 0.15.11 (Minecraft 1.20.1 and +)

**Comment by MichaelHillcox** [comment]
Looks like fabric already has a good selection of their own inventory sorter mods. I'd recommend using one of those. There is no real reason for this mod to expand into the fabric space when that space already has an offering.

For example: https://www.curseforge.com/minecraft/mc-mods/inventory-sorting

**Comment by jasonlam510** [comment]
My friends and I frds have been using your mod and switched to inventory-sorting because of the mod loader migration from Neoto Fabric, we all agree that your mod is better! I think the download count of your mod has proven that your mod is better than inventory-sorting (75.9M vs 18.1M in CurseForge). 

As a software engineer, 
> There is no real reason for this mod to expand into the fabric space when that space already has an offering.

This sounds to me like: We are doing well in IOS and there are others option in Andriod so we give up the Android user.

I just hope you can understand that your mod is so great and it's good to be more compatible so that more people get benefits.
