### ISSUE TITLE
[Suggestion] Ability to customize sorting

### ISSUE THREAD

**Issue by Lethann** [cpw/inventorysorter#37]
Playing SF3 and right now when I click the sorting button it simply sorts by quantity. I really REALLY wish I could change this to sort by Mod or item type FIRST then quantity. I know not everyone wants this but the option to change how it actually sorts would be nice.

**Comment by cpw** [comment]
I'll look at adding it. Quantity sort is always my preferred sorting, but it's just a comparator change, so it should be easy.

**Comment by PapiDimmi** [comment]
Yes, please!

You should be allowed to sort by any of the following things:
* Name (alphabetically)
* Item type
* Mod
* Quantity

**Comment by scottcher** [comment]
I'd like this option too.  quantity sorting is useful but sometimes other options are more important to me on the fly.  Even if it started with a config option to tweak the default sorting method without being able to select sort-mode on the fly would be useful.

Making it nested would be a special bonus - ie, Mod then Name then Quantity or any combination.

**Comment by VapourDrive** [comment]
I second this, I actually couldn't figure out what in the world it was sorting based on, I use quantity for nothing. Mod ID is the most helpful I find, as it groups mod's items together

**Comment by IngmarBitter** [comment]
Yes. Please add this. One key drawback of sorting by quantity is that the actual order changes all the time. With sorting by ItemID things will remain in about the same place when new items are added to the inventory - and similar items end up next to each other. Both are features I look for in good sorting.

**Comment by 4rz0** [comment]
I too would prefer sorting after names.
Ideally, there'd be a few options to choose from.

**Comment by cpw** [comment]
Yeah, I really need to get around to this

**Comment by dclay1983** [comment]
Not trying to insult, but I am actually curious why anyone would ever want a default sort to be something that would always change, quantity sorting becomes as random as just picking things up.

**Comment by IronPiston** [comment]
Are there any plans still to add this?

**Comment by Karanime** [comment]
Hi. Your CurseForge page doesn't allow comments. Hopefully I can reach you here. Yours is currently the only inventory sorting mod on 1.14 and it would be useful to have different or custom sortings. Currently when I try to sort a chest with only one of each item, sorting looks completely random, instead of putting like items next to each other (e.g. stairs of different materials).

**Comment by LeftofZen** [comment]
Quantity sorting is the worst kind of sorting. Item ID/Name would be far more useful, then perform a secondary sort on quantity/other params if needed. I'd change the code/make a pull request myself if the code wasn't so impenetrable.

**Comment by Old-Man-D** [comment]
This is still a thing that is needed.  When I try and sort chests from AFK fishing, all the fish go to the top because of their stack size, but everything else is just a random order.  Books are not with books, bows are not with bows, etc.  It's all just a jumbled mess.

**Comment by Kaboom4224** [comment]
I would suggest sorting by item id (alphabetically) but inverting the id before sorting

what i mean is instead of sorting "acacia_button", you sort "nottub_aicaca"
this will have the effect that no matter the wood type used all buttons will be next to one another (instead of having all acacia items next to one another)
other examples of this would be logs or armour

List of ids: https://minecraft.gamepedia.com/Java_Edition_data_values

**Comment by HyperionCoding** [comment]
Since this is the only inventory sorter for 1.15.2 I decided to add sorting by item ID which is what I like to use personally too. This is the first time I even touch Java so I'm not going to commit the changes.

What I added is sorting by number ID and namespaced ID. It mostly uses existing code and doesn't remove old functionality but I had to delete some sortings because it actually sorted by size at least 3 times. Because I haven't ever made Minecraft mods I couldn't add config but there are placeholder booleans that control the sorting and maybe @cpw wants to implement those.

For reasons above stated, here's the plain downloads for altered files and two compiled versions, one with ID sorting and second by namespaced ID.
https://www.dropbox.com/sh/nynd9wl6s5jhwzv/AACG8Cy5OS6ZFG1vXw29hPSha?dl=0

**Comment by balloonhead** [comment]
still not added sorting by ID or Name? I agree that sorting by just the number of items isn't effective.

**Comment by JakeMoe** [comment]
Hopping in here to add my +1; love inventory sorting, but sorting by quantity is (imho) unhelpful, as you never know where to find the thing you're looking for, and checking quantities is easy once you found them.  I would think straight by item name would be most useful, like Applied Energistics (and I think Refined Storage?) does.  I can see how some people might want by mod as well.  Even by ID (like JEI) would be more useful, as things would still be in the same order all the time.

**Comment by balloonhead** [comment]
4 years without reply on this. Anyone with an alternative?

**Comment by seema84** [comment]
why was the issue closed?
