### ISSUE TITLE
Dont crash with Forge 28.1.19, but dont work

### ISSUE THREAD

**Issue by JFGTX** [cpw/inventorysorter#81]
So now, its not crashing when i launch the game with the newest version of IS, but the mod doesnt still work at all for the time :/ But few good news ^^

**Comment by 0lm** [comment]
its because of forge. would be actually great if forge were downwards compatible with all forge versions for a certain MC version. i hope they will do that one day so you dont need to stay on an older foge version just because you need to run one single mod, but all other 10 mods you like are not working with that one. lol.

best combination for this mod to work is: the current recommended forge version (28.1.0) and inventory sorter v 15.3. this combination works fine with mc 14.4.4. and alot othermods also support the current recommended fore version, so the majority of possible favourite mods should also work.

**Comment by cpw** [comment]
Current IS is compatible with latest forge builds.
