### ISSUE TITLE
console errors on connect (Netty Epoll Server ERROR / Could not serialize)

### ISSUE THREAD

**Issue by Radecal** [cpw/inventorysorter#87]
whenever I or someone else joins the following is thrown up in remote console

this is what shows when I join
04.12 08:20:22 [Server] Netty Epoll Server IO #12/ERROR [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@176fe21b (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
04.12 08:20:22 [Server] Netty Epoll Server IO #12/ERROR [minecraft/ArgumentTypes]: Could not serialize cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument@53f6d29b (class cpw.mods.inventorysorter.InventorySorterCommand$ContainerClassArgument) - will not be sent to client!
04.12 08:20:22 [Server] Netty Epoll Server IO #12/ERROR [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@49e8fcd (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

this is what shows when others join 
02.12 01:28:58 [Server] Netty Epoll Server IO #15/ERROR    [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.ModIDArgument@2a57e616 (class net.minecraftforge.server.command.ModIDArgument) - will not be sent to client!
02.12 01:28:58 [Server] Netty Epoll Server IO #15/ERROR    [minecraft/ArgumentTypes]: Could not serialize net.minecraftforge.server.command.EnumArgument@31599836 (class net.minecraftforge.server.command.EnumArgument) - will not be sent to client!

no visible problems in game however sometimes other warns/errors will show up during gameplay
will update with log when I see it next.

**Comment by sollswl** [comment]
I am having the same issue. But everything is going well in the game. Running server 1.16.1 w/ forge 32.0.98.

**Comment by afurey0** [comment]
Same issue on 1.18.1 server. I am getting disconnected shortly after seeing this message, but I don't know if this is the cause yet.

**Comment by magnusjjj** [comment]
Hi. Why was this closed? The issue still exists :).

**Comment by JuhoF1N** [comment]
> Hi. Why was this closed? The issue still exists :).

Indeed, I am getting this currently also on my All the mods 7 latest version server (version ending in 2.37) and getting disconnected a while after

**Comment by magnusjjj** [comment]
Actually, I straight up ripped out that part of the mod. It no longer throws an exception, but the loading problems persist.

Looking *at* the error it seems like it's a generic error thrown to warn about an incompatibility with vanilla. You can suppress the warning, which most mods do. That it throws the exception at that point is just.. unlucky?

I am no closer to figuring out which mods in the modpack I am running is the cause of my actual errors, because in my case it only crashes on join randomly, and netty doesn't specify what channels it's expecting.

For CPW, I would suggest suppressing the exception like other mods do, and to, uhm, add a comment when closing issues so people like me and the other's don't think they are assholes because of unlucky circumstantial logs, but it's not really their fault. Probably. Could be elsewhere of course, but eeeeh.

**Comment by ingie** [comment]
If you're going to use a 3 year old non important issue on github, to say you think a developer is an asshole for not following your way of doing things - don't.

**Comment by magnusjjj** [comment]
I am not saying that the developer is an asshole. I am saying that it *looks* like it and other users have commented like it on other issues marked with it, expressing frustration.

He is going to *keep* getting reports raised because *any* mod that crashes on the client side on load where, oh, it's because of an unregistered packet, is going to *look* like its inventorysorters fault because inventorysorter *always* throws an exception in the logs when joining, and is, at least in the pack I am using, the only mod that does so. To then just close issues without commenting again and again is Not The Best(tm). Either fix it or copy paste some statement.
