### ISSUE TITLE
doesnt seem to want to create a config file in the config folder ?

### ISSUE THREAD

**Issue by carlucci9660** [cpw/inventorysorter#88]
doesnt seem to want to create a config file in the config folder ?

**Comment by stfwi** [comment]
Hi cpw, I had the same issue and took a glance in to the mod code. Could this be related to the config registration line in the mod constructor ...

```
ModLoadingContext.get().registerConfig(ModConfig.Type.SERVER, Config.SPEC);
```
... to ...
```
ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Config.SPEC);
```
... for single player internal server usage (or is that e.g. planned to be changed in the Forge)?

---
***1.14.4***:
`versions: mc1.14.4, forge-28.2.0, inventorysorter-1.14.4-16.2.0`.
I get a startup exception due to a missing config instance when sending blacklists via IMC to, log attached - for completeness, my IMC sending code is:

```
private void onSendImc(final InterModEnqueueEvent event)
{
  InterModComms.sendTo("inventorysorter", "containerblacklist", ()->ModContent.MY_CONTAINER_TYPE.getRegistryName());
  InterModComms.sendTo("inventorysorter", "slotblacklist", ()->MyCraftingOutputSlot.class.getName());
  InterModComms.sendTo("inventorysorter", "slotblacklist", ()->MyCraftingGridSlot.class.getName());
}
```
[2020-02-21-logs-1.14.4.zip](https://github.com/cpw/inventorysorter/files/4236263/2020-02-21-logs-1.14.4.zip)

---
***1.15.2***:
`versions: mc1.15.2, forge-31.1.1, inventorysorter-1.15.2-17.0.0`.
IMC works, no startup exception, but no config file created for single player / builtin server.

Cheers, wile -
